### ISSUE TITLE
Add email notification feature

### ISSUE THREAD

**Issue by AndrewCFD** [fsepy/fdspy#1]
I have recently enabled emailing from the modelling servers, therefore it would be great if we could add this feature into the auto submission feature.

My thought is that when you submit a job you use something like the following string so we add the -e feature:

fdspy sbatch -v 674 -e user@company.com

Then in the back end, we jsut need to add the following 2 lines to the submit.sh script if the -e flag is used (the email address would obviously change based on the user):

#SBATCH --mail-type=BEGIN,END
#SBATCH --mail-user=user@company.com

**Comment by fuyans** [comment]
Added. See 71e9221.
